
server {
    listen 80;

    location = / {
        return 301 /physical_activity_log/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /physical_activity_log/index.html;
    }

    error_page 404 /physical_activity_log/index.html;
}
